name: CMake

on:
  push:
    branches:
      - huhao1987-patch-1
  pull_request:

env:
  BUILD_TYPE: RelWithDebInfo
  VCPKG_DEPS_REVISION: 65ef3a6db0e01983efc7d8286f44020beeee2ea3

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Add OpenMW PPA Dependencies
      run: |
        sudo add-apt-repository ppa:openmw/openmw -y
        sudo apt-get update

    - name: Install Building Dependencies
      run: sudo CI/install_debian_deps.sh gcc openmw-deps openmw-deps-dynamic

    - name: Prime ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ubuntu-${{ env.BUILD_TYPE }}
        max-size: 1000M

    - name: Configure
      run: |
        cmake . \
        -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
        -D OPENMW_USE_SYSTEM_RECASTNAVIGATION=ON \
        -D USE_SYSTEM_TINYXML=ON \
        -D BUILD_COMPONENTS_TESTS=ON \
        -D BUILD_OPENMW_TESTS=ON \
        -D BUILD_OPENCS_TESTS=ON \
        -D CMAKE_INSTALL_PREFIX=install

    - name: Build
      run: cmake --build . -- -j$(nproc)

    - name: Run Components Tests
      run: ./components-tests

    - name: Run OpenMW Tests
      run: ./openmw-tests

    - name: Run OpenMW-CS Tests
      run: ./openmw-cs-tests

    - name: Install OpenMW
      run: cmake --install . --prefix ./install

    - name: Create OpenMW Archive
      run: |
        tar -czvf openmw.tar.gz -C install .

    - name: Upload OpenMW Archive
      uses: actions/upload-artifact@v4
      with:
        name: openmw.tar.gz
        path: ./openmw.tar.gz
